#!/usr/bin/env node

/* Module dependencies. */
const debug = require('debug')('api:server');
const http = require('http');
const app = require('./app');
const {
  normalizePort,
  onError,
  onListening,
} = require('./functions/server.func');

/*  Create HTTP server. */
const server = http.createServer(app);

/*  Get port from environment and store in Express. */
const port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

/* Listen on provided port, on all network interfaces. */
const listener = () => onListening(server, debug);
server.listen(port);
server.on('error', onError);
server.on('listening', listener);
